import Head from "next/head"

import Feed from "@/components/Feed"
import Header from "@/components/Header"
import Modal from "@/components/Modal"

const Home = () => {
    return(
        <main>
            <Head>
                <title>Instagram Clone</title>
                <meta name="description" content="Instagram Clone - Generated By (Next.js , Tailwind css , Firebase)"/>
            </Head>

            {/* Header */}
            <Header/>

            {/* Feed */}
            <Feed/>

            {/* Modal */}
            <Modal/>

        </main>
    )
}

export default Home